---
- name: Playbook - Ansible 101 Certification | Jonathan Wilson
  hosts: localhost
  connection: local
  gather_facts: false

  vars: #define variables available to all tasks
          astronauts: "{{ lookup('url', 'http://api.open-notify.org/astros.json') }}" #fetch astronaut data from a URL and store it in a variable 
          greeting: "Welcome home Space Crew!  You must be hungry !"
          dinner_time: True
          dinner_selection:
            - "Pizza"
            - "Tacos"
            - "Steak and Potatoes"
            - "Fried Chicken"
            - "Le Big Mac"

  tasks:

          - name: Display Ansible Welcome Banner
            script: ~/alta3research-ansible-cert/scripts/welcome.pl
            args:
              executable: /usr/bin/perl
            register: welcome_banner


          - name: Display the Welcome Banner
            debug:
              var: welcome_banner.stdout_lines


          - name: Fetch Github Repo Details
            script: ~/alta3research-ansible-cert/scripts/githubinfo.sh
            register: github_repo_details
          

          - name: Display the Github Repo Details 
            debug:
              var: github_repo_details.stdout_lines
                

          - name: Display Greeting to the Space Crew
            debug:
                    msg: "{{ greeting }}"
            

          - name: Display Crew member name and craft name from http://api.open-notify.org/astros.json and randomize
            debug:
                    msg: "{{ item.name }} from the space craft {{ item.craft }} has arrived. They are guest {{ ansible_loop.index }} of {{ astronauts.number }} ."
            loop: "{{ astronauts.people }}" #loop through the JSON list
            loop_control:
              extended: true


          - name: Is it dinner time? #if it is dinner time then let's get the crew fed!
            debug:
                    msg: "Guess what time it is?!  That's right - it's dinner time!!  Let's get the crew fed with one of our great randomly selected meals."
            when: dinner_time|bool


          - name: Display Crew member name and craft name from http://api.open-notify.org/astros.json and randomize their dinner selection
            debug:
                    msg: "{{ item.name }} will be having {{ dinner_selection|random }} for dinner this evening."
            loop: "{{ astronauts.people }}" #loop through the JSON list
            when: dinner_time|bool

          
